### ISSUE TITLE
NoiseTorch stuck "Working"

### ISSUE THREAD

**Issue by SleepingFox88** [lawl/NoiseTorch#11]
## Issue

https://streamable.com/u4uk4m

Upon hitting ``load noiseTorch`` Noisetorch never exits the "working" screen, and pulseAudio loads two new audio output devices (one of them named null) before crashing

I am aware the ReadMe acknowledges this issue under the "troubleshooting" section but it also says it will work if you restart, yet my issue doesn't seem to fix after a dozen application restarts and one system restart.

## System Information

I am running

Distro: Manjaro Linux
Kernel: 5.4.44-1-MANJARO
Front End: Cinnamon v4.6.3
GPU: GeForce GTX 1080
Graphics drivers: nvidia-440.xx

**Comment by lawl** [comment]
I have a suspicion what that is and it unfortunately sounds like this issue mentioned in the readme:

> Unfortunately, sometimes NoiseTorch may display a "Working..." screen forever when loading the virtual microphone. This is usually due to PulseAudio crashing. If that happens, close NoiseTorch and try again, that usually works. I am working to improve this situation.

With that said, I'd like to confirm this and see if we can get a work-around going for you.

First thing I need you to do is check the realtime rlimit of pulseaudio like this.  
Find the `pid` of the pulseaudio daemon running as your user like this:

    $ ps ux | grep pulseaudio
    user        8519  4.3  0.1 1564784 20104 ?       S<sl 06:42   0:09 /usr/bin/pulseaudio --daemonize=no --log-target=journal
    user        8620  0.0  0.0  18800   728 pts/1    S+   06:46   0:00 grep --color=auto pulseaudio

So in my case the PID is **8519**. Then run `cat /proc/8519/limits` and make sure to substitute the correct PID in.

We're interested in the last line here, which in my case sais:

    Max realtime timeout      200000               200000               us        

If it has a number for you too (doesn't say 'unlimited'), write it down then proceed like this:

Edit the `/etc/pulseaudio/daemon.conf` as root and find a line like

    ; rlimit-rttime = 200000

Remove the `;` to uncomment it, and set it to `-1` (=unlimited).

    rlimit-rttime = -1

Save this, then restart pulseaudio with `pulseaudio -k`. Now repeat the first two steps to check the rlimits of the process. If done correctly the last line should now say:

    Max realtime timeout      unlimited            unlimited            us        


Then test if NoiseTorch loads correctly now.

Note, you will want to revert that setting it may cause your sound *and* random applications to freeze for an arbitrary amount of time. But it'll help us confirm if this is the issue.

**Comment by vn-ki** [comment]
Hi, not op, but your instructions fixed the issue for me.

**Comment by anomalyce** [comment]
Sorry for hijacking, but I experienced the exact same issue. Your workaround did solve it for me (outputs were exactly the same as your examples, i.e. 200000).

Distro: Arch Linux
Kernel: 5.7.8-arch1-1
WM: i3 4.16.1-184-g00181678
GPU: XFX Radeon RX 590 Fatboy

Let me know if I can be of any more service or if you need any more information about my system.

Thank you for the software!

**Comment by lawl** [comment]
@anomalyce @vn-ki 

Hey, awesome, I do however strongly recommend to *not* use the value of `-1` forever. If this fixed it for you, I suggest you up the default value of `200000` until you find one that works for you (remember to `pulseaudio -k` in between). Having to too high or even unlimited is a bad idea, as it can make arbitrary applications freeze for an arbitrary amount of time.

I'd like to find a better solution for this long term, but upping this value should can hopefully serve as a work-around in the meantime.

**Comment by anomalyce** [comment]
Thought I might share some additional information.. but I want to prefix it by saying that audio is my arch-nemesis and I have no idea what I'm doing when it comes to audio.

I tried incrementing the value from 200,000 by an additional 100,000 at a time. First success in loading was at 1,000,000, but was unable to unload it. Tried increasing yet another bit, this time to like 1,500,000 and suddenly none of it worked (loading/unloading). I kept raising it substantially and the results seemed inconsistent throughout. I went as far as 100,000,000.

-1 always seems to work however. Again, this may be because I've done something to mess up my audio setup as I have no knowledge at all when it comes to audio. But happy to help further debug in case you want me to!

PS. All the commas in the numbers are just for reading purposes. They weren't used in the actual `/etc/pulse/daemon.conf` file.

**Comment by lawl** [comment]
@anomalyce 

Can you upload your `/tmp/noisetorch.log`? I'm particularily interested in

> was unable to unload it

as this is the first time I hear unloading not working. 

If possible also some of your pulseaudio log

    journalctl -n300 --no-pager -b /usr/bin/pulseaudio

Best to put them in a [gist](https://gist.github.com/)

**Comment by anomalyce** [comment]
I only got it working a couple of times without using -1, and only once of those times unloading didn't work (in the GUI anyway).

`/tmp/noisetorch.log`
https://gist.github.com/anomalyce/8ce8ea198c941892afccb3a8df784cc2

`journalctl -n300 --no-pager -b /usr/bin/pulseaudio`
https://gist.github.com/anomalyce/b4973a2a20991ad5aa218a5964c0aaab

I did run `pulseaudio --start` after `pulseaudio -k` because I've had issues with it not restarting occassionally so that may explain the `Daemon already running.` messages.

You also underestimate my ability to mess things up ;-)

**Comment by lawl** [comment]
I see. It seems some systems are just super sensitive to this issue and yours seems so sensitive that it even triggers on unloading. May I know what CPU you're running?

a dump of `cat /proc/cpuinfo` would be awesome. Also, are you running on an SSD or hard drive?

My speculation at the moment is that this hits harder the weaker the system is.

**Comment by anomalyce** [comment]
I've got an Intel i7 5820k, https://gist.github.com/anomalyce/a668988ee219898a98014266ec729a1a and the OS is installed on a Samsung 950 Pro NVMe.

**Comment by lawl** [comment]
Huh, so it's definitely not a case of a weak system causing this. I'll have to wait for more feedback from other people too for the moment, sorry.

**Comment by anomalyce** [comment]
Absolutely, not a problem. Cheers for the help thus far! :-)

**Comment by starcrATI** [comment]
Hey!
I've gotten the same inconsistent results like anomalyce with changing the  rlimit-rttime values in the daemon.conf.
`-1` followed by a `pulseaudio -k` worked, but didn't for other values, no matter how high (except for a couple of not reproducable times).
But with rlimit-rttime commented out again, and a stock config of `200000`, it works when I run `pulseaudio --start` before opening NoiseTorch.
Then I just have to restart Firefox, in order for it to be able to find any microphones.

**Comment by lawl** [comment]
@starcrATI 

Thanks for the report.

I'm currently working on an experimental feature that sets the `RTTIME` to unlimited via syscall for the short duration where modules are being loaded and unloaded, this is probably the best we can do, plus if thing do freeze, it can be fixed by a reboot and doesn't require editing configs to get the system booting again in the absolute worst case.

I will (hopefully soon) provide an experimental build here for people with this issue to try out.

As this issue cannot be fixed without redesigning from scratch how pulse handles modules, I do not see another way.

**Comment by lawl** [comment]
Could those affected affected by thing bug try out a new build?

(Sorry for pinging you all @starcrATI @anomalyce @vn-ki @SleepingFox88 )

If you have the work-around enabled in your pulseaudio config, please disable it for this test.

I can only attach zip files here, so here's a zip with just the binary:
[noisetorch.zip](https://github.com/lawl/NoiseTorch/files/4938360/noisetorch.zip) unpack this anywhere and mark it as executable with `chmod +x noisetorch` then run it. (If it says update available, ignore it)

If you prefer to build from source [here is the source](https://github.com/lawl/NoiseTorch/tree/setrlimit)

So this build of noisetorch requires that you have `pkexec` installed on your system, which should be most distributions, to elevate to root privileges so it can temporarily remove the rlimit set on pulseaudio. When you click Load you should get a promp for your password (it's legit, i swear, check the code :P).

It currently does *not* do this for unloading which @anomalyce reported to also be a problem, but I've tried to address this otherwise. Please let me know if that works for you or if you need any additional infomation.

**Comment by anomalyce** [comment]
I undid the workaround and I'm getting the following:

```bash
2020/07/17 16:44:53 Application starting. Version: 0.3.4-beta
2020/07/17 16:44:53 Checking if config needs to be initialized
2020/07/17 16:44:53 Wrote temp librnnoise to: /tmp/librnnoise-721584517.so
2020/07/17 16:44:53 Checking for updates
2020/07/17 16:44:55 Querying pulse rlimit
2020/07/17 16:44:55 Rlimit: {Cur:200000 Max:200000}. Trying to remove.
2020/07/17 16:44:55 Calling: /usr/bin/pkexec /home/anomalyce/Downloads/noisetorch -removerlimit 96914
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/home/anomalyce/Downloads/noisetorch' as the super user
Authenticating as: anomalyce
Password:
==== AUTHENTICATION FAILED ====
2020/07/17 16:44:58 Couldn't remove rlimit as root: exit status 127
2020/07/17 16:44:58 Rlimit: {Cur:200000 Max:200000}
2020/07/17 16:44:59 Loading supressor
2020/07/17 16:44:59 Loaded null sink as idx: 27
2020/07/17 16:45:00 Loaded ladspa sink as idx: 28
```

**Comment by anomalyce** [comment]
I undid the workaround and I'm getting the following:

```bash
2020/07/17 16:44:53 Application starting. Version: 0.3.4-beta
2020/07/17 16:44:53 Checking if config needs to be initialized
2020/07/17 16:44:53 Wrote temp librnnoise to: /tmp/librnnoise-721584517.so
2020/07/17 16:44:53 Checking for updates
2020/07/17 16:44:55 Querying pulse rlimit
2020/07/17 16:44:55 Rlimit: {Cur:200000 Max:200000}. Trying to remove.
2020/07/17 16:44:55 Calling: /usr/bin/pkexec /home/anomalyce/Downloads/noisetorch -removerlimit 96914
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/home/anomalyce/Downloads/noisetorch' as the super user
Authenticating as: anomalyce
Password:
==== AUTHENTICATION FAILED ====
2020/07/17 16:44:58 Couldn't remove rlimit as root: exit status 127
2020/07/17 16:44:58 Rlimit: {Cur:200000 Max:200000}
2020/07/17 16:44:59 Loading supressor
2020/07/17 16:44:59 Loaded null sink as idx: 27
2020/07/17 16:45:00 Loaded ladspa sink as idx: 28
```

I am correctly entering my password.

**Comment by lawl** [comment]
@anomalyce Weird, can you try this one: 
[noisetorch.zip](https://github.com/lawl/NoiseTorch/files/4938445/noisetorch.zip)?

I'm not sure what that error is, I'm now explicitly passing `--user root`.

**Comment by anomalyce** [comment]
I am an idiot. Please disregard my previous comment. I had to define a polkit rule to allow the use of pkexec. I'm attaching the rule for anyone else in a similar situation. _Please bear in mind that this may leave you vulnerable to other things, so be cautious and use at your own risk._

```bash
# /etc/polkit-1/rules.d/50-noisetorch.rules

polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.policykit.exec" && subject.isInGroup("wheel")) {
    	return polkit.Result.YES;
    }
});
```

With this in place, both of your binaries seem to work! Thank you!

**Comment by lawl** [comment]
@anomalyce Awesome! Hopefully I can get a few more confirmations that this works and then I can polish it and release it.

**Comment by starcrATI** [comment]
@lawl Seems to do the trick for me aswell! :)

**Comment by lawl** [comment]
0.4.0-beta is out now which ships this fix.
