### ISSUE TITLE
is it possible to load noisetorch on startup?

### ISSUE THREAD

**Issue by tprei** [lawl/NoiseTorch#116]
I really like NoiseTorch and Id like to make it load on startup, is there some sort of API for doing that?

**Comment by lawl** [comment]
See: https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd

Yes, you can do it, but it's deliberately not single-click at the moment because of unnecessary CPU usage which may be especially a problem on laptops because of battery life etc. If you're on a desktop system and don't mind permanently "wasting" a few % of one core, then follow that wiki guide.

**Comment by lawl** [comment]
I assume this is solved now.
