### ISSUE TITLE
problem with building the aur package

### ISSUE THREAD

**Issue by barfin** [lawl/NoiseTorch#124]
Yes I know you said don't use aur package, but I don't wanna use it, I wanna maintain and fix it
it would be great if you could help and tell me what should change to make it compile successfully
https://aur.archlinux.org/packages/noisetorch/

**Comment by lawl** [comment]
are you asking because you're having a specific problem, or are you asking why i tell people to not use the AUR package?

**Comment by barfin** [comment]
> are you asking because you're having a specific problem, or are you asking why i tell people to not use the AUR package?

nothing needs to be changed about your recommendation against using the aur
but some people including me will use aur anyway so I adopted the package to keep it up to date
looks like the previous maintainer has used some patch to make it work which looks like this
https://aur.archlinux.org/cgit/aur.git/tree/main.patch?h=noisetorch
however this seems to be broken in newer releases and gives this error
```
patching file main.go
Hunk #1 FAILED at 25.
1 out of 1 hunk FAILED -- saving rejects to file main.go.rej
```
I wanna know what's your recommendation to fix this issue

**Comment by lawl** [comment]
If you need to change something to build a distribution package, I'd prefer if, instead of every distribution applying their own "slightly wrong in a different way" patch, you could upstream a mechanism here to make these things configurable so that they're usable for all distros.

The previous maintainer had an issue where the version number of the current build system could not be fetched because it's built from a tarball and not the git repo. As this example demonstrates again, these patches are not very robust and a frequent cause of breakage.

I would strongly prefer to extend the build system so that an override string can be passed. Extending the build system so it can be called with e.g. `make VERSION="420.6.9-AUR"`. This can then be upstreamed and used by all third party packages.

**Comment by gavtroy** [comment]
Ideally the tarball should build without needing to add a `VERSION=xxx`. The issue is that crrently the tarball doesn't build at all without patching.

The "please do not use [the AUR]" note is not helpful because it's counter to how the (Arch) Linux ecosystem works. From a user's perspective NoiseTorch is just another program and shouldn't need its own rules. It's unfortunate NoiseTorch has seen bad packaging but it shouldn't overshadow the benefits of packaging done well.

**Comment by lawl** [comment]
The tarball is a feature github automatically provides and not one that I support. I'm more than happy to discuss options if someone has suggestions on how to fix the problem upstream, meaning here, and is willing to contribute a solution.

Open Source doesn't mean you get support and i fix all your problems for you. It means you get the code under a license with no warranty etc.

If the arch people want to convey noisetorch, they can, under the license, meaning they do it here and contribute back, or they mark their fork as a clear fork. So far they haven't been willing or able to contribute here.
