### ISSUE TITLE
How to query NoiseTorch status from CLI

### ISSUE THREAD

**Issue by benjaminvdb** [lawl/NoiseTorch#165]
I know there's a `noisetorch` CLI, but it doesn't support querying the status, as far as I can tell. What I'm trying to achieve is to figure out:

1. Whether NoiseTorch is running
2. If so, to which device it is connected

This would allow me to write a simple widget for my status bar (i3bar) that allows me to select a device and activate/deactivate NoiseTorch from it.

**Comment by lawl** [comment]
1 There was a PR to add checking the status [here](https://github.com/lawl/NoiseTorch/pull/91) which i declined at the time. But pipewire turned out different than i thought at the time, so this could be added now.

2. not a fan. we'd need to parse the device id out of the pulseaudio parameters again, and while certainly possible, i feel it will create a bunch of issues down the line that i don't really want to deal with.

**Comment by benjaminvdb** [comment]
@lawl Thanks for your quick response! Good to hear (1) is an option. If (2) can't be implemented reliably, then I understand you're not going to support it.

How do you suggest I integrate NoiseTorch with other tools? If this isn't going to be officially supported, it would be helpful to know where I should look. You seem to point that the pulseaudio parameters contain the necessary info, how do I fetch these?

**Comment by lawl** [comment]
@benjaminvdb you should be able to parse the device ID out of one of the `argument` lines when running `pacmd list-modules`. But yeah, your parsing will rely on what I consider implementation details and may change at any time. I currently don't have any plans to change that code because there's no reason to. But I do want to point out that this is entirely unsupported and may break at any time with no advance warning.
