### ISSUE TITLE
Noisetorch with discord cause a lot of cpu spike and system hang [Pop OS 20.04]

### ISSUE THREAD

**Issue by tr1p0p** [lawl/NoiseTorch#166]
Since a while, it's seem discord and noisetorch cause massive cpu spike when i'm using it on my system.

I run Pop Os 20.04 (ubuntu-based) and got last discord install with deb and last noisetorch release.

Where's screen from cpu states from system monitor:

![cpu panic](https://user-images.githubusercontent.com/37407065/127696796-d18e6792-6732-4420-990e-8c48a4bdb147.png)

EDIT : so, i run a few test and it's seem it's the same with flatpack version of discord, however not having this issues with web app discord. so, yeah i thing it's more discord related, even if with my mic without noisetorch, discord don't do cpu spike. here screen from htop.
![htop](https://user-images.githubusercontent.com/37407065/127712935-e2786404-2a8a-4261-a3db-4081bb0c08c8.png)

**Comment by lawl** [comment]
according to that htop screenshot, pulseaudio is at 22% cpu. (the actual denoising is injected into the pulseaudio process), some CPU load is expected, because well, it needs to do the actual denoising which is somewhat CPU intensive.
We don't talk to discord ourselves, so i have no idea what discord could be doing here to make it's CPU usage go up. Nothing i can do here, sorry.
