### ISSUE TITLE
Echo is there in  Discord if Discord and Brave use the mic.

### ISSUE THREAD

**Issue by UtkarshVerma** [lawl/NoiseTorch#174]
If I'm on a Discord call during a Google Meet on Brave, my meet audio is somehow routed to Discord voice chat, and I don't hear anything from the meet, but my friends on Discord VC can.
If I unload and reload Noisetorch, the issue goes away, but doing this all the time becomes annoying.

I'm using Void Linux with pulseaudio.

**Comment by lawl** [comment]
what's set as your default microphone?

**Comment by UtkarshVerma** [comment]
I have manually set Noisetorch as default in Discord, and Brave picks up the systemwide default which is my sound card `Family 17h (Models 10f-1fh) HD Audio Controller)`.

**Comment by UtkarshVerma** [comment]
This are the inputs I have, just for your reference.

![image](https://user-images.githubusercontent.com/31820255/131294371-8fdbf29b-4d6b-40fa-80ae-a2d22e75d681.png)

**Comment by UtkarshVerma** [comment]
I think I've figured out why this is happening. When noisetorch is active, somehow Brave assigns new tabs to the Null output created by noisetorch.
I am only using noisetorch for filtering mic.

**Comment by lawl** [comment]
> somehow Brave assigns new tabs to the Null output created by noisetorch.

that's not something i have control over. the null output especially is not supposed to be used by anything, other than noisetorch itself internally. But because of how pulseaudio works, it's there and can be selected. You'll need to figure out yourself how to get your applications/system to stop using it. Nothing I can do here sorry, this is entirely out of my control.
