### ISSUE TITLE
Plans for a aur package?

### ISSUE THREAD

**Issue by alx365** [lawl/NoiseTorch#2]
Any plans? anyone?
maybe i could also make one... or the owner doesn't want a aur package ¯\_(ツ)_/¯. Would definitely suck

**Comment by lawl** [comment]
I am not opposed to an AUR package, but I don't want to build packages for every distro.

If someone wants to package NoiseTorch, go ahead, there's a few things to watch out for though. NT ships it own update infrastructure, and this expects that NT is installed in the users `$HOME` and not as a system application.

Updates can easily be disabled, so there is no inherent limitation here. So distro packages would either need

A) A separate build with updates disabled. My preferred option, so the distro name can also be stuck into the version number, e.g. `0.3.2-beta-arch`. Reason: Makes it easier to find package specific issues.

B) Simple command line flag to disable updates, and then distro's ship a wrapper and put that in the `.desktop`

**Comment by alx365** [comment]
You could make a aur package, which **just**, builds it from source, installs it, and never updates it, because it has a native updater.

**Comment by lawl** [comment]
Sure, people are welcome to do that. I currently have no plans to create distro-specific packages, but I'm certainly not opposed to them.

**Comment by erbrecht** [comment]
> B) Simple command line flag to disable updates, and then distro's ship a wrapper and put that in the `.desktop`

What would that command line flag be? I've got a package in the aur, but it installs to the system's `/usr/bin` and /usr/share` directories so auto-update will break.

**Comment by alx365** [comment]
umm i am rn working on a aur package, would be stupid if both of us worked on it

**Comment by alx365** [comment]
But i also have some questions, the release .tgz file, how do you create it, is there some script? i looked around a bit, but couldn't find anything. My aur package would: 

1. build from source
2. (if possible) make the release .tgz file
3. run that just like described in the readme

Like that i wouldn't have to update the aur package everytime you update noise torch, and the user could use the auto updater.

**Comment by erbrecht** [comment]
https://aur.archlinux.org/packages/noisetorch-bin/

It's been there since earlier this morning. It's just using the binary release, so if you were planning on doing a source build, they would definitely be different.

**Comment by alx365** [comment]
oh cool, didn't check the aur yet... (kinda stupid from me)

yeah mine could be the 'git' release

**Comment by lawl** [comment]
@erbrecht The commandline flag currently doesn't exist. I could add `-noupdate` and then you could ship noisetorch as `noisetorch.real` and add a wrapper script as `noisetorch` that calls `noisetorch.real -noupdate`. Does that make sense?

@alx365 

`make release`

**Comment by alx365** [comment]
oh ok thanks.

How about a PR, which adds make uninstall, and which just runs the four lines from the README?

**Comment by lawl** [comment]
@alx365 

Doesn't make sense to me as there is no make install, please open a separate issue if you want to discuss this further.

**Comment by alx365** [comment]
hmm true...

**Comment by alx365** [comment]
ok when building from source, it returns this error:
```
panic: open /home/user/.config/noisetorch/private.key: no such file or directory
```

**Comment by erbrecht** [comment]
@lawl that does make sense. I could also patch the desktop entry to add the flag to the `Exec` command. There would be a couple ways to accomplish that.

If you provide a flag I will probably use that. I'm not sure what the difference is between using the updater and fetching the latest release tarball. They're all your updates, right? Some people may prefer to have pacman handle updates. It's not my intention to start an argument, I'm just curious why it makes a difference.

If you really prefer that a binary aur package use the updater, I might abandon the `-bin` version in favor of the package @alx365 produces.

**Comment by lawl** [comment]
Yes, release tarballs for updates are signed so that if someone compromises the update server or I lose the domain, they can't ship updates.

You can generate your own private key with `go run scripts/signer.go -g`. Note that of course the signature verification will still fail, because my public key is hardcoded in the source (on purpose), but it should get you past the error. And the signature is just a separate `.sig` file that you can then throw away.

**Comment by lawl** [comment]
@erbrecht The difference is that there is a separate wrapper in place. And say I introduce more command line options but a wrapper forgets to pass `"$@"` (just an example) then I get bug reports that the command line option isn't working.

The reason is that I would prefer distro packages to have the distro name in the version number so that if a lot of bugs suddenly come in with version number `12.34-voidlinux` I can look if there's an issue with the package, instead of searching for impossible bugs in NT.

**Comment by alx365** [comment]
> manages updates itself
do you mean people can update by updating the aur package, or the inbuilt updater?

> can get a source build working
that's what i am working on.

So i managed to build it with the key, but, because of the hardcoded key, does that mean that you can't compile it yourself, and produce a usable version, and you have to use your compiled version?

**Comment by lawl** [comment]
No, it only means noisetorch would reject this as an update package if you would somehow manage to feed this to everyone using the built in updater. That and running `go run scripts/signer.go -v` would report the signature as invalid.

Again this is only relevant for the self updater as a security measure. You could fork the repo and replace my key with yours. But unless you plan to setup your own update server, it wouldn't change anything.

**Comment by alx365** [comment]
So self compiled, while still using the auto update system, is not possible.

In that case, @erbrecht 's package, is the better one, if we manage to install on user level, not on root level.

**Comment by lawl** [comment]
No you're not understanding, but I don't know how else to explain this to you.

**Comment by alx365** [comment]
whats now the exactly the limitation of self compiling?

**Comment by erbrecht** [comment]
i don't like the idea of a package that is installed through pacman, that then uses an update system outside of pacman. it kind of defeats the whole point of the package manager. installing in the user location means more configuration needs to be done to get the noisetorch binary into the path. i could provide a base config file that includes `EnableUpdates = false`. that would prevent updates without requiring a flag to be passed.

@lawl i know you said you really prefer keep the binary release updated through your update mechanism, but this kind of conflicts with the role of the package manager. if this were an official package it would be built from source, so this wouldn't be a problem.

my initial plan was to build a `-bin` version and a `-git` version, the latter being built from source. since @alx365 is already doing the source version, i don't want to duplicate efforts. if you want to collaborate on a source-based aur package, i'd be more than happy to do that

**Comment by lawl** [comment]
> if this were an official package it would be built from source, so this wouldn't be a problem.

Yes that is my point. If you want to provide a package, please do it right. I do not want the additional support maintenance for things that are repackaged in a way that it was not designed for.

**Comment by alx365** [comment]
Tbh, i underestimated the workload coming to me, when i wanted to make the aur package, while i can compile it already and install it. i don't really feel like now going through all of the pain of the update system. I already made a basic package (https://aur.archlinux.org/packages/noisetorch/, you'll have to install some more dependencies), but, as i said, i don't want to do the stuff with the update system, and i want to drop out. Should i transfer the ownership @erbrecht , since you were actually planning on doing also the source package, and i don't want to anymore. Sorry for all the questions that i asked, that are now rendered useless >.<

**Comment by lawl** [comment]
@alx365 

    	echo "currently you can't use the audo updater. Because you compiled it from source." 

The updater should work perfectly fine with that script.

**Comment by erbrecht** [comment]
> > if this were an official package it would be built from source, so this wouldn't be a problem.
> 
> Yes that is my point. If you want to provide a package, please do it right. I do not want the additional support load for things that are repackaged in a way that it was not designed for.

you're missing my point: aur packages aren't **official** packages. arch linux takes no responsibility for them. you wouldn't be supporting the package, i would. It is also specifically designed with the ability to disable the update feature. i'm not sure how i'm repackaging this in a way it wasn't designed. put the files in the filesystem, disable the update checker, done.

binary package distributions are good for those who don't want to deal with all the dependencies required to build from source. if @alx365 doesn't want to work on the source based package, i can pick that up and get it working. i'm not sure how to transfer an aur package to another person, but we'll figure that out

**Comment by alx365** [comment]
i can look into it, your aur uname is the same as here after all

**Comment by alx365** [comment]
> The updater should work perfectly fine with that script.
No it doesn't, it doesn't correctly install because i haven't looked into how to install on user level and not on root (thats how it currently does)

**Comment by lawl** [comment]
Alright, I think I'm removing myself from this discussion, I don't have anything to add that I haven't said yet. So people interested in building an AUR package can coordinate themselves here in peace.

**Comment by alx365** [comment]
Ok thanks, for all the help until now!

**Comment by alx365** [comment]
@erbrecht i have added you as a co maintainer, you should be able to pull the package, upadate something random and push it.
[picture](https://i.imgur.com/vyFuLUf.png)

**Comment by erbrecht** [comment]
@alx365 i created a new package called noisetorch-git. that follows the guidelines listed here

https://wiki.archlinux.org/index.php/VCS_package_guidelines

i made you a co maintainer on that one as well.

both the -bin and -git versions are available in the aur. the -git version is building from source and is setting the enable update flag to false. in the -bin version, i added a post_install message letting the user know about the auto update issues.

**Comment by alx365** [comment]
Ok i'll remove my current package.

**Comment by alx365** [comment]
Umm forget it, there was a request to remove it already. and now its just gone. Were you that? Or was that a trusted user, because it was a shitty package, and i shouldn't have uploaded it, because it didn't even work yet.

**Comment by erbrecht** [comment]
wasn't me, but i did notice it wasn't showing up when searching the aur. maybe a TU

**Comment by alx365** [comment]
Yeah it was a trusted user, he told me some stuff that was wrong with it, and he was right, it wasn't complying with the terms of the aur.

**Comment by lawl** [comment]
Can this be closed then?

**Comment by erbrecht** [comment]
Yeah, you can close it. Thanks for the help.

**Comment by eli-schwartz** [comment]
Thanks for getting this re-uploaded correctly.

BTW: @lawl usually for C programs one would have a configure/meson/cmake/other script which would set some `#define` that enables the auto-update code. I believe you can use go build tags to similar effect? This would be best for distro users as it would not require either manual config settings or potentially confusing wrappers.

**Comment by lawl** [comment]
@eli-schwartz yes, I think that's how we should be doing this, which requires that distro packages build from source, which is unfortunately where the conversation got stuck before, so we never got to this.

Yes we provide a build tag for this, and I would accept a PR adding this. Or if someone wants to open an issue for me to add this, I will eventually, but have other priorities right now.

**Comment by lawl** [comment]
@erbrecht Can you please fix this patch: https://aur.archlinux.org/cgit/aur.git/tree/config.patch?h=noisetorch-git

This is not how this should be done. The correct patch to remove updates is to remove these three lines: https://github.com/lawl/NoiseTorch/blob/master/main.go#L66

Also please restore the actual default flag in your users configuration in their home directory. I'm considering how to improve installation methods, and messing with the default config may unexpectedly break things for users. Especially if e.g. they switch from AUR to some other method.

Otherwise I'm forced to include code specifically for this AUR package, which is exactly what I was trying to avoid here. Not happy.

**Comment by erbrecht** [comment]
If I remove those lines and someone changes distros, taking their home directory with them, they will never be able to enable automatic updates. It will be left in a more broken state than if I change the user-editable config file.

I will certainly make this change, but I don't see how this is in any way preventing the issues you are talking about. A new package should be up in the next day or 2.

**Comment by lawl** [comment]
They don't take the binary with them as you don't install it in their home, so yes, a binary from a different source with the existing config will work just fine.

Thanks,

**Comment by erbrecht** [comment]
Doh, totally overlooked that. I'll let you know when the new package is available.

**Comment by erbrecht** [comment]
New package is published. You also mentioned wanting the distro name in the version so it would be easy to distinguish from other packages/builds. Any advice on how to do that? I'd be glad to add it.

> So please restore the default config in their home directory, otherwise I'm forced to include code specifically for this AUR package, which is exactly what I was trying to avoid here. Not happy.

If the build/installation process changes, I'll update the package accordingly. I do read the release notes when I see a new release is available. I don't think you need to add code just for this package at this point, but just let me know if something needs to change. I think I've been pretty responsive so far.

**Comment by lawl** [comment]
Thanks, I'm a bit confused because now you seem to not remove the updater at all?

And the problem with the current configuration is not just that you are breaking users possibly in a future release, but you are already breaking them *now*, if they decide to use a different binary, because you silently flipped a manual override for them, and now there's no knowing which user set it manually, and for which ones you just set it. So I would prefer you could reset your users to the actual default value.

**Comment by erbrecht** [comment]
i'm patching `main.go`, removing the following 3 lines:

```go
if ui.config.EnableUpdates {
    go updateCheck(&ui)
}
```

Is that not sufficient? As far as I can tell the current PKGBUILD contains the patch file and actually runs it, removing the update check.

I added a comment to the package page, letting people know that they should update their config so it matches the intended defaults. I could similarly add a message post-install. I hesitate to modify a file that is not owned by the package, but I'm looking to get some feedback on that from the community.

**Comment by lawl** [comment]
>Is that not sufficient?

Absolutely is, my bad, must have looked at the wrong package. Sorry!

**Comment by eli-schwartz** [comment]
> I hesitate to modify a file that is not owned by the package, but I'm looking to get some feedback on that from the community.

Your instinct was correct, it is forbidden by policy for pacman packages to modify user $HOME behind the user's back. For several reasons, including the fact that it's behavior characteristic of malware, the fact that you cannot know which user performed the installation, and the fact that multiple users may be present. Failing all that, you cannot know which users had a setting automatically applied and which ones did so manually.

post_upgrade **echoed messages** are the recommended method here.

**Comment by lawl** [comment]
@eli-schwartz The file was *already* modified behind the users back, which now forces me to deal with this. No, a postinstall message is not good enough. And to be quite frank, i personally really don't care what policies AUR has.

The solutiin then is to to explicitly warn about using 3rd party packages that haven't explicitly been blessed and make usage of those 'void warranty'.

**Comment by eli-schwartz** [comment]
Which file was modified behind the users' back? My understanding was the stock/default config file was changed, something that only affected (for better or worse) a) new users b) who didn't manually tune their configs.

Obviously this is... non-ideal... I really don't think distros should change how config files work like this. Reacting by using root processes to scan user homedirs and replace those settings just in case they were victims of this isn't any better though, and comes with unique problems including several viciously bad security issues when editing user-controlled files as root.

Third-party packages are always "void warranty", in my opinion as a distributor of rather a lot of third-party packages. :)

**Comment by erbrecht** [comment]
No problem, glad the correct version is up there.

The file wasn't modified behind the user's back. noisetorch generated the config file; the code that noisetorch uses to generate that file was modified. It sounds like semantics, but the package didn't put the config file in place, so it shouldn't be making changes to it.

> and now there's no knowing which user set it manually, and for which ones you just set it.

I may have screwed up creating the package like that in the first place, which is obviously completely on me. I'm putting forward my best effort to make it right though. The package is barely over a week old so I think any fallout from this would be extremely minimal.

**Comment by lawl** [comment]
> The file wasn't modified behind the user's back. 

Yes it was. And yes it's semantics. Not arguing about this.

> Third-party packages are always "void warranty", in my opinion as a distributor of rather a lot of third-party packages. :)

Go look at some bugtrackers then to see if users realize that.

But this solves this then. I will recommend against using AUR, move anything mentioning AUR on the issue tracker to `/dev/null`, if you don't think it's to tell users what happened and force them to make an informed choice.

Ideally I would also prefer for you to rename the package and application and not call it noisetorch. But i do not hold a trademark and cannot force you to do that, it's just a friendly request.

**Comment by erbrecht** [comment]
I've already said I would add a post upgrade message telling users to update their config. Even if the package owned that config file, I wouldn't be able to force an update. Other distros wouldn't either. They would just create a .pacnew, .rpmnew, etc and it would be up to the user to merge the changes.

Is adding the post upgrade message, as well as the comment on the package page, not enough at this point? I honestly don't know what else I can do, aside from just pulling the package altogether.

**Comment by lawl** [comment]
I'm done with dealing with AUR at this point. I have better ways to waste time. Please consider my last request.

**Comment by lawl** [comment]
@erbrecht As a heads up. With the next release of NoiseTorch, you will have to either stop applying patches, or rename, as will other distributions.

I have learned that in accordance with GPLv3 section 7, this is in fact a restriction i'm allowed to add. Although, I find it sad that I have to and just asking wasn't enough.

You can find the upcoming license changes here: https://github.com/lawl/NoiseTorch/commit/8b054c20a909c9cc459e87ee8b56226c0428201b


I'm giving you this heads up so you have time to decide and or talk to arch people what you/they want to do.

**Comment by erbrecht** [comment]
Thanks for the heads up. We're working on it, and we'll certainly comply with this restriction.

**Comment by lawl** [comment]
@svenstaro 

I don't have an AUR account so I'm replying here:

> I'm not really sure where this hostility from upstream is coming from. I suppose you can just rename it to not-noisetorch and move on with this. :p what a silly upstream move.

You can do that. I can also simply stop providing software for free under the GPL. If you think me taking NoiseTorch from OpenSource to Source Available under a proprietary license is better, then yes. Name it that.

The only hostility I see here is an incredible disrespect for whishes I have for software that I wrote and am giving away for free. No, I don't want downstream to apply patches and call it NoiseTorch, be that Arch or another distro. I don't want users to come to this bugtracker then and report issues that may have been caused by any number of distros applying broken patches. I don't want users to think NoiseTorch has bugs that may have been introduced downstream.

The GPL realizes this and gives author an explicit tool against it with section 7. This is also not a new issue, I'm sure you're familiar with [IceWeasel](https://en.wikipedia.org/wiki/Mozilla_software_rebranded_by_Debian). You can apply all the patches you want if you call it IceTorch or something and I really don't care.

Or you can choose to act in bad faith. Go ahead. I'll just remove all GPL code contributed by others and take it proprietary Source Available, surely that would be better for everyone.

**Comment by svenstaro** [comment]
Arch Linux tries very hard to only apply the minimal amount of patching necessary to properly package a software downstream. It's even in [our core principles](https://wiki.archlinux.org/index.php/Arch_Linux#Principles). We want to work _with_ upstream, even in cases such as this where upstream unnecessarily assumes bad faith. In this particular case, @erbrecht wanted to de-vendor your software.

We try very hard to not come across as disrespectful towards upstreams and ask the same kind of respect in return. After all, we're trying to make your software available to our users in a safe and centralized manner here, we should be working together.

At this point in the thread, I'm not really sure where the problem really is anymore and I'm not sure you're interested in us in distributing this. Do you think we can reach some kind of agreement here that allows us to make the necessary, minimal changes to noisetorch so that it'll run for our users and will still allow us to call it by the canonical name?

**Comment by lawl** [comment]
> We want to work with upstream, even in cases such as this where upstream unnecessarily assumes bad faith

I have trouble understand naming it "not-noisetorch" would not be acting in bad faith.

> In this particular case, @erbrecht wanted to de-vendor your software.

Yes and I don't want that as long as you call it NoiseTorch. Please respect my wishes.

> After all, we're trying to make your software available to our users in a safe and centralized manner here, we should be working together.

I fully agree, though I've yet to see anyone from the Arch side working with me here, but only offloading work to me.

> At this point in the thread, I'm not really sure where the problem really is anymore and I'm not sure you're interested in us in distributing this. 

As I've said before. I don't want downstream modifications if you call it NoiseTorch. It's really as simple as that.

> Do you think we can reach some kind of agreement here that allows us to make the necessary, minimal changes to noisetorch so that it'll run for our users and will still allow us to call it by the canonical name?

If these changes are necessary and minimal, why don't you try upstreaming them so other distributions can profit from them too? I think that would be in the open source spirit, wouldn't you agree?

**Comment by hashworks** [comment]
> I have trouble understand how naming it "not-noisetorch" would not be acting in bad faith.

I'm sure that was irony.

> I fully agree, though I've yet to see anyone from the Arch side working with me here, but only offloading work to me.

It should be noted that the AUR is entirely unsupported and does not host official Arch Linux packages. If you think the posted PKGBUILD violates your license you are of course free to request a removal.

> If these changes are necessary and minimal, why don't you try upstreaming them so other distributions can profit from them too? I think that would be in the open source spirit, wouldn't you agree?

Would you accept a PR that removes the shared object binary inclusion upstream?

**Comment by lawl** [comment]
> It should be noted that the AUR is entirely unsupported and does not host official Arch Linux packages. If you think the posted PKGBUILD violates your license you are of course free to request a removal.

It currently doesn't because I can't (and don't want to) retroactively change the license. If AUR is supported or not here is also entirely irrelevant to the discussion.

> Would you accept a PR that removes the shared object binary inclusion upstream?

No, but I would probably accept a proper patch that makes this configurable at build time and then you could add a `make distro` build target that all distros can use. I'd imagine the requirements are pretty similar for all distros.

**Comment by anthraxx** [comment]
> > After all, we're trying to make your software available to our users in a safe and centralized manner here, we should be working together.
> 
> I fully agree, though I've yet to see anyone from the Arch side working with me here, but only offloading work to me.
> 
> > At this point in the thread, I'm not really sure where the problem really is anymore and I'm not sure you're interested in us in distributing this.
> 

I frankly and honestly without offense, have the feeling you are exclusively being focused on yourself so far while people actually try to cooperate with you. Different parties have different needs and requirements. A good and healthy communication and interaction with upstream means to work *together* -- which ultimately means to meet in the middle of certain requirements and different points of view of the involved parties. Nobody wants to offload work purely on you and nobody here is acting in bad faith. But you need to see that distros have certain requirements as well.

**Comment by lawl** [comment]
> Nobody wants to offload work purely on you and nobody here is acting in bad faith. But you need to see that distros have certain requirements as well.

I'm sure you can point to to a pull request from a distribution then that helps everyone?

**Comment by anthraxx** [comment]
> > Nobody wants to offload work purely on you and nobody here is acting in bad faith. But you need to see that distros have certain requirements as well.
> 
> I'm sure you can point to to a pull request in noisetorch from a distribution then that helps everyone?

Frankly read through your posts, you didn't quite stated in an welcoming way that you would accept any patches meeting our requirements. You basically went on a full nuts all in war instead, how would you expect anyone to spend time on a patch you so far denied allowing? Stating that you are open for such a change is the ground that people will try to get a PR ready.

**Comment by lawl** [comment]
> Yes we should provide a build tag for this, and I would accept a PR adding this.

**Comment by kbabioch** [comment]
That is probably one of the worst upstream interactions I've encountered so far. Epic discussion, time for some :popcorn: 

I guess we can thank @Scrumplex for working on a viable solution and trying to bring together the different opinions here (:+1:), although it seems to me that @lawl seems to have a very unusual understanding of FOSS.
