### ISSUE TITLE
[Feature:] Allow Multi-input with priority

### ISSUE THREAD

**Issue by arouzing** [lawl/NoiseTorch#228]
Thanks for making such an awesome project! I was wondering if it could be possible to have multiple inputs at the same time. Let me give my reasoning as to why this is useful. 

## Scenario:
You have a headset and desk mic. Sometimes you get up and walk away wanting to use your headset mic. Then when you get back you want to auto switch over to the desk mic like nothing happened. in the UI you would have numbered selections of priority for audio where one supersedes the other muting the other mic when it detects audio from the first. Currently I'm using helvum as a patch bay but I have to reconfigure it after every reboot. 

Thanks again for your time!

**Comment by lawl** [comment]
> Currently I'm using helvum as a patch bay but I have to reconfigure it after every reboot.

I think a patchbay is probably the correct place to do what you describe here. To do that on noisetorch side we'd also basically have to implement a patch bay. So I think it makes more sense to do that there. 

> but I have to reconfigure it after every reboot.

is that an inherent limitation of your tooling, the audio server, or noisetorch? If theres some reasonably easy fix i can apply to make this work i'm more than happy to, i just don't feel like noisetorch is the correct place for complex audio routing setups like you describe.

**Comment by arouzing** [comment]
I think this is a limitation of my tooling. That being said the feature was an idea because adding it would simplify the workflow for that particular use case. 

Is it an easy fix? I'm not particularly sure is would be. To simplify it it could just be limited to allowing multi sources at one time.

If you know of a method with permanence to merge audio sources with pipewire I'm willing to try them.

What section of your code allows for selecting the audio source? It may be reasonably do-able to allow multi source.

Thanks for taking your time to read this!

**Comment by lawl** [comment]
We just tell pulse which device ID to use. That's done here: https://github.com/lawl/NoiseTorch/blob/master/module.go#L239

You might be able to set both microphones to output to `nui_mic_raw_in` by loading another `module-loopback`. I don't see any immediate reason why that wouldn't work. But it's definitely not something that's supported. If that does work, you might be better of using this: https://github.com/werman/noise-suppression-for-voice with your own custom script to set things up.

I'll close this in the meantime, since as i said, i will probably never support that officially in the GUI.
