### ISSUE TITLE
noistorch for windows

### ISSUE THREAD

**Issue by jalal26** [lawl/NoiseTorch#236]
i have no clue how github works so i will just ask here
 i needed to switch to windows for school and  i have a loud family and the background noise is quite loud 
 and it distrubs the class its so bad that the teacher doesnt even  call me for answers knowing how loud it is gonna distrub class 
 if u can make a  windows version that would be nice

**Comment by lawl** [comment]
Making a windows version would involve paying microsoft hundreds of dollars for a code signing license, either for a driver, or a DLL so we can inject into processes like chrome.

I don't feel like paying microsoft money to make their ecosystem better, sorry.

**Comment by sedyh** [comment]
> Making a windows version would involve paying microsoft hundreds of dollars for a code signing license, either for a driver, or a DLL so we can inject into processes like chrome.
> 
> I don't feel like paying microsoft money to make their ecosystem better, sorry.

Sounds very strange, there is no barrier to just publishing a build in releases for other platforms

**Comment by Technetium1** [comment]
Typically unsigned binaries have more limited features, and are often blocked entirely in corporate environments. If you want something for Windows explicitly; pay for something like established - like Krisp.

> Sounds very strange, there is no barrier to just publishing a build in releases for other platforms.

Welcome to submitting to the will of a half-trillion-dollar corporation. If you use their platform you must play by their rules, even if their rules are trash. Maybe consider a VM with Linux host and forward the mic source to VM.

**Comment by TheDukeofErl** [comment]
It's also worth noting that even if we made a build for Windows it wouldn't do a whole lot. NoiseTorch-ng is fully reliant on Linux audio subsystems and isn't portable to Windows. With that in mind, this is something that is truly a wontfix. I can't imagine this getting any development time and, personally, I'm not sure I'd want to accept a PR that tries to do this.

> Maybe consider a VM with Linux host and forward the mic source to VM.

I kind of wonder if WSL 2.0 would do anything or work at all. That said, I don't use Windows so I'm in no position to test that.

**Comment by Technetium1** [comment]
I don't think that'd be quite as simple as a VM. The downside to using WSL is you can't also use another hypervisor simultaneously. Here's how to get pulse working if you did want to go down the rabbit hole https://www.linuxuprising.com/2021/03/how-to-get-sound-pulseaudio-to-work-on.html

**Comment by snipeTR** [comment]
Hello,

First of all, I would like to thank you for developing such a useful and effective project like NoiseTorch. Your technical approach and the solution you’ve created in this field are truly impressive. Making a technology like RNNoise this practical and accessible requires a high level of expertise.

I’d like to share an idea and an observation with you.

I believe there is currently a significant gap, especially on the Windows side. There are commercial solutions like Krisp, but there is almost no open-source, transparent, and accessible alternative. In this regard, I think you are one of the few developers with the knowledge and capability to fill this gap.

Instead of jumping straight into a large development effort, it might make sense to treat this first as a way to test interest. For example, by launching a small campaign on a platform like Kickstarter, you could clearly measure:

* How much real demand there is
* How much people are willing to pay for such a product
* What the market expectations look like

There is also another important situation in the market: solutions like Krisp have gradually expanded their scope and started adding many extra features to justify higher pricing. For example:

* Meeting transcription (speech-to-text)
* AI-generated meeting notes and summaries
* Additional effects beyond noise suppression, such as echo cancellation and background voice modification
* Call analytics and productivity tools
* Meeting recording and organization features

While some of these features can be useful, many users actually just want clean microphone audio. Despite this, these extra functions increase the overall cost, and users often end up paying for features they don’t even use.

For this reason, a solution that does just one thing really well — low-latency, high-quality, and simple noise suppression — could be a strong alternative both technically and commercially. I believe there is real demand for a simpler, more transparent, and more affordable approach.

I also don’t think this is only a commercial opportunity. If successful, the revenue and user base you gain could allow you to contribute much more strongly to the Linux ecosystem. You could dedicate more time to open-source projects, further improve tools like NoiseTorch, and potentially create even more advanced audio processing solutions on the Linux side.

In a way, it could be possible to build a sustainable model where revenue from Windows users helps support and grow the Linux ecosystem. This would be highly valuable for both the open-source community and users.

Speaking personally, I’m very satisfied with NoiseTorch when using Linux. However, when I have to use Windows, I struggle to find a comparable solution. That’s why an initiative like this could make a significant difference for both individual users and a wider audience.

Maybe this will remain just an idea, or maybe it could be the beginning of something much bigger. Either way, I believe it is definitely worth considering.

Thank you again for your work and contributions.

**Comment by Technetium1** [comment]
@snipeTR https://sourceforge.net/projects/equalizerapo/ + https://github.com/werman/noise-suppression-for-voice
