### ISSUE TITLE
Is it possible for noisetorch to process and output stereo audio

### ISSUE THREAD

**Issue by WerLunar** [lawl/NoiseTorch#248]
Hi lawl,

I have a stereo microphone and I find noisetorch is recognized as mono input in OBS. The stereo mic is selected as norisetorch input.
![Screenshot from 2022-05-03 04-34-05](https://user-images.githubusercontent.com/68589810/166306505-9d33ad82-2f4b-447b-bc0c-35364d183ae5.png)

Is it possible to make noisetorch work with stereo audio?
I'm running noisetorch on Ubuntu 22.04, linux 5.15, pipewire

And thanks so much for your effort creating and maintaining such a great linux noise reduction application. :)

**Comment by lawl** [comment]
nope. noisetorch only outputs mono. I have experimented with doing it stereo, but you don't want it, trust me.

The problem is that the left and right channel then sound unnaturally different, because we need to process each channel individually. Meaning e.g. L might be completely silent, but on R you still have noise etc. It's really jarring. Mono is actually just better.
