### ISSUE TITLE
Add support for pipewire

### ISSUE THREAD

**Issue by tuxPT** [lawl/NoiseTorch#63]
NoiseTorch doesn't start on pipewire even with pulseaudio dropin replacement.  Please add support

**Comment by lawl** [comment]
* Is there any distro already shipping pipewire?
* When do major distros plan to ship it?

**Comment by tuxPT** [comment]
I think no one. I am using sway with pipewire in a ArchLinux system.

**Comment by lawl** [comment]
PipeWire is on my radar, but it will be low priority until adoption starts.

**Comment by ZyanKLee** [comment]
Fedora has a change proposal to switch to pipewire for their release 34 in 2021:
https://fedoraproject.org/wiki/Changes/DefaultPipeWire

I think those are the first planning to do this switch by default.

**Comment by lbibass** [comment]
Garuda Gnome also uses pipewire by default.

**Comment by lawl** [comment]
Started to look into this. Likely to be a significant amount of work, especially because PW is new and we can't rely on existing code.
I quickly talked to wtay the maintainer of PipeWire and he said in theory PW could emulate everything so that NoiseTorch PulseAudio works out of the box with its PulseAudio emulation.

Personally I hope that essentially rewriting NoiseTorch for PipeWire would solve some issues that are simply artifacts of how we have to do things under pulse, such as requiring root/`CAP_SYS_RESOURCE`. So I think it would be better to essentially rewrite things for PipeWire.

There's still a bunch of open questions on how we will handle that transition that I haven't fully made up my mind on yet. Open questions:

a) Should we have separate binaries for PA/PW version?

Things to consider here: Maintenance, one codebase that needs to do two completely different things could become ugly. But separate codebases could end up copy pasting UI stuff. But the UI's might end up different anyways because from the first look PA/PW approaches to things are quite different, but they also might not.

b) Will the Pulse version go EOL?

Depends if PW will be universally adopted. I think the general plan is that PipeWire replaces pulse, but things don't always go according to plan, or take way longer than expected *cough* Wayland *cough*
This again has impacts on if PW should be a separate code base.

So my current thinking is that I'll try to get a usable POC ready by the time fedora ships PipeWire, and then we'll wait and see how the PipeWire situation ends up looking.

If anyone has thoughts on this, I'd be happy to hear them.

**Comment by lbibass** [comment]
Could it be possible to use WirePlumber as a way to ease the transition? https://gitlab.freedesktop.org/pipewire/wireplumber

I'll be honest, I have no experience with the Linux audio subsystem.

**Comment by AlexFolland** [comment]
PulseEffects, despite having "Pulse" in the name, now only supports PipeWire.  This has caused me on Manjaro to want to switch to PipeWire as well, since I need PulseEffects for a system-wide equalizer to fix my speakers' excessive bass.

NoiseTorch not supporting PipeWire is the only thing preventing me from switching to PipeWire, since I need NoiseTorch to fix my 13-year-old headset's constant waterfall noise, which it does very nicely.  It makes my microphone sound like it's new.

If NoiseTorch did the same as PulseEffects and dropped PulseAudio support entirely, that would hasten the transition to PipeWire, even if by a small amount.  If this was done, though, I recommend leaving a PulseAudio branch available that contains the last version that supports PulseAudio, for easy packaging.

Thank you for your consideration of this.  Also, thank you for making NoiseTorch.

**Comment by lawl** [comment]
I currently have no plans of dropping PipeWire support. And small update. I have a POC for pipewire running, far from finished though and not shippable as it still requires lots of manual setup.

I will try to strike a balance between the "it just works" goal of noisetorch (I know we aren't there yet) and not wasting too much effort on legacy systems. But for now my plan is to support both, ideally from a single binary, so "it just works" and you don't need to know the internals of your OS to download the correct version.

**Comment by RafaelKr** [comment]
@AlexFolland for PipeWire support you can use version 5.0 of PulseEffects or version 4.8.4 for PulseAudio support. Both support the "Noise Reduction" filter using RNNoise, the same library NoiseTorch uses.

**Comment by Taza53** [comment]
ngl noisetorch justs feels better and I miss it on pipewire.

**Comment by tuxPT** [comment]
> @AlexFolland for PipeWire support you can use version 5.0 of PulseEffects or version 4.8.4 for PulseAudio support. Both support the "Noise Reduction" filter using RNNoise, the same library NoiseTorch uses.

the problem is that pulseeffects has to much latency because, I think, basically they are still using gstreamer, that supports pipewire and thus not a optimized implementation. I can't watch any video with pulseeffects the audio has like 1-2 sec latency.

**Comment by AlexFolland** [comment]
I have since switched to PipeWire with PulseEffects, and I don't have that issue.  The audio latency seems identical to not using PulseEffects, which is imperceptible.

**Comment by lawl** [comment]
I've talked to wtay (pipewire author/maintainer) about some issues i was encountering. As I've said before, I do have a POC running on pipewire, and most of the work I did there, already went back into the main NoiseTorch repo with 0.10.0. I have a filter running on PipeWire that works fine, but you manually need to "wire" it up on the PipeWire graph. For users this can currently be done with Jack tools such as Catia.

The issue is that wiring things on the node graph is currently way more annoying than it should be imo. It's absolutely doable, and you can see e.g. PulseEffects has done so. That said, i'm not sure I want to do that. PipeWire in its current form causes some headaches for how we currently do things.

* NoiseTorch needs to keep running in the background, which it currently doesn't. Some work on the UI would be required here to make it always run in the background - doable. The CLI is much more problematic here, because it's build on the assumption that it can tell pulse to do some stuff and then be gone. With PipeWire we would need to run as some kind of service in the background. This would require either a noisetorch daemon, or changing the CLI.

* NoiseTorch currently ships without dependencies such as libpulse, because we use a reimplementation in Go. PipeWire would require either linking to libpipewire, or partially reimplementing it. In the first case we would need to transition from our current deployment model to using something like AppImage. Either option is doable, but not an insignificant amount of work.

wtay indicated that better APIs are coming and NoiseTorch should be able to just work on the pulseaudio layer in the future (will still likely require some small changes in NT, but nothing big).

With these things considered, I don't think it makes sense to make such drastic changes if PipeWire is still relatively immature and things are still likely to change. I have seen PulseAudio being pushed out too early and if Fedora does push PipeWire out too soon, I personally rather stay on pulse a bit longer.

I will at this point not add PipeWire support. For the time I'd rather explore options such as contributing to PipeWire to add better APIs.

Your options are using PulseEffects which has similar capabilities (I don't think it does Voice Activity Detection unfortunately), or you can use the proof of concept code I wrote in C for the pipewire filter here: https://github.com/lawl/ntpipewire and connect it on the graph manually using jack tooling, such as [Catia](https://kx.studio/Applications:Catia).

**Comment by CorePoint** [comment]
Thanks for all your work and effort!

**Comment by Azumix** [comment]
Just saw this thread after the upgrade of Fedora to 34 and wondering why Noisetorch was not usable anymore. Make sense now. Still, thanks for your work on this software.

**Comment by lawl** [comment]
A dependency on pipewire doesn't mean anything by itself. You can use pulseaudio for sound and pipewire for video side by side.

I don't have any news on pipewire from my side. My stance is still that any distro rolling it out now as a pulse replacement is doing so too early. I've seen that with pulse itself, and I personally don't want to suffer through that again. PipeWire support will come, but not right now. Unless of course someone else wants to work on it. I currently don't as I'm staying on PulseAudio for the time being.

**Comment by lawl** [comment]
If you're very adventurous you can now test a very early alpha of NoiseTorch on PipeWire.
If you're not that adventurous, the answer is soon™.

Adventurous as in, you will need to build both NoiseTorch and PipeWire from source code. PipeWire very recently (like, a day ago) pushed some things that make the implementation pretty easy for us, but it's not in a release yet, you need to build the master branch.

Additionally, you need to build the [NoiseTorch pipewire branch](https://github.com/lawl/NoiseTorch/tree/pipewire) from source.

Also, expect bugs, on our side, and pipewire's.

![image](https://user-images.githubusercontent.com/680451/118118255-f6d8f700-b3ec-11eb-9e6c-13031c967dbc.png)

**Comment by YodaEmbedding** [comment]
Will it be possible for the PipeWire port of NoiseTorch to only run when a program is recording? A [Pulseaudio issue](https://github.com/lawl/NoiseTorch/issues/41#issuecomment-664007786) inhibited this, but is it possible for PipeWire?

**Comment by lawl** [comment]
@YodaEmbedding  i believe it shouldn't consume (a lot of) CPU when nothing is using it as pipewire fundamentally uses a pull model while pulseaudio just pushes data through. No consumer=nothing get pulled. A quick test seemed to indicate this is indeed the case.

But don't quote me on this.

**Comment by lawl** [comment]
PipeWire 0.3.28 has been released: https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/NEWS

Meaning NoiseTorch 0.11.0 has been released which supports PipeWire now: https://github.com/lawl/NoiseTorch/releases/tag/0.11.0

This is alpha quality support at this point. Please manage your expectations and report bugs.
