### ISSUE TITLE
Does noisetorch support stereo mic input?

### ISSUE THREAD

**Issue by BurntBrunch** [lawl/NoiseTorch#65]
I'm unable to get NoiseTorch to support either of the microphones connected to my computer, I get completely empty output on both. The only common factor is that they're both stereo mics. Is this a supported configuration?

I'm running a very plain and uncustomized Fedora 32

**Comment by lawl** [comment]
Pulseaudio *should* downmix stereo to mono and it *should* work. That said, I've encountered quite a few issues with cases where pulseaudio *should* downmix/resample audio. It seems to.... not work very well.

It would be trivial to add stereo support and denoise both channels, but that can lead to weird behaviour where one channel is silenced and the other one isn't, which i personally found to be quite jarring.

Then there's also the issue that some microphone lie about being stereo, *cough* mine *cough* while in reality they're mono, but if we treated these as stereo we'd use twice a CPU and actually achieve lower quality than if we just force it to be mono.

So I'm not quite sure how to handle that, but I'm also not really sure that this is your issue.

So let's confirm that first, here's a build that forces stereo mode instead of forcing mono mode. Let's see if that's even the issue first.

[noisetorch.zip](https://github.com/lawl/NoiseTorch/files/5514875/noisetorch.zip)

If that doesn't work, the output of `pacmd list-modules` and `pacmd list-sources` with that build and noisetorch loaded may be helpful.

**Comment by BurntBrunch** [comment]
Okay, something has definitely changed between 0.7.0 and 0.7.3. Your version, as well as 0.7.3-beta both work. Apologies for not retesting before posting.

Interestingly, amplitude is way higher with the stereo build you provided but that's not enough of a problem for me to care about right now. 

Thanks for your time! Closing as resolved.
