### ISSUE TITLE
Gnome menu entry is not displayed under Pop!_OS 20.04

### ISSUE THREAD

**Issue by Sulavius** [lawl/NoiseTorch#96]
If NoiseTorch is the first application in ~/.local/bin/, the Gnome menu entry is not displayed because the noisetorch.desktop file does not point to an executable application.

This can be fixed by logging back into Pop!_OS 20.04 or by manually adjusting $PATH.

My suggested solution would be a note in README.md that under these circumstances, if noisetorch is not yet in the PATH, no menu entry will be displayed.

Also the icon key in the noisetorch.desktop file is not specified correctly. I have already tested the proposed change.

Output: desktop-file-install
`error: (will be fatal in the future): value "noisetorch.png" for key "Icon" in group "Desktop Entry" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path`

**Comment by lawl** [comment]
> My suggested solution would be a note in README.md that under these circumstances, if noisetorch is not yet in the PATH, no menu entry will be displayed.

There is a mention to check the path, but you're right, the path beeing added with a snippet like this in the readme before the directory exists will require re-logging. So I think it makes sense to add that.

> error: (will be fatal in the future): value "noisetorch.png" for key "Icon" in group "Desktop Entry" is an icon name with an extension, but there should be no extension as described in the Icon Theme Specification if the value is not an absolute path

I'm pretty sure i've checked the spec before and this wasn't actually true. I was pretty sure this was explicitly allowed but I just rechecked the spec and it's a bit more complicated than that. The suggested algorithm does indeed implement it that way in pseudocode, but the spec sais 

> If the name is not an absolute path, the algorithm described in the Icon Theme Specification will be used to locate the icon. Implementations may choose to ignore it.

Here: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example

So the spec does not in fact say that the icon must not have an extension.

So, since it doesn't actually cause any issues, I will leave it like that and rather find a better way to distribute NoiseTorch (AppImage etc.)

**Comment by lawl** [comment]
ReadMe has been updated. Thanks for the issue!
